TrainingArguments:
  output_dir: "pegasus-samsun"
  num_train_epochs: 1
  learning_rate: 5e-5
  warmup_steps: 500
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  weight_decay: 0.01
  logging_steps: 10
  eval_strategy: "steps"
  eval_steps: 500
  save_steps: 1000000
  gradient_accumulation_steps: 16