artifacts_root: artifacts

data ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Turvash/Datasets/raw/refs/heads/main/zip_dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
